# Generated by Django 2.2.2 on 2019-06-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollar',
            name='delta',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dollar',
            name='value_at',
            field=models.DateField(),
        ),
    ]
